GET http://localhost:3000/posts
?userId=1
&limit=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoiZGVsZXRlQGdtYWlsLmNvbSIsImlhdCI6MTcyNzM1MDAzMywiZXhwIjoxNzI3MzUzNjMzLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.20TsLBMQSiCt_tTHgTk7rmKCuGaapsR7O5BWP1bGcgY
GET http://localhost:3000/posts/1