GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoiZGVsZXRlQGdtYWlsLmNvbSIsImlhdCI6MTcyNjc5MDk1OCwiZXhwIjoxNzI2Nzk0NTU4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.jHAwksuN2BFcREo3LpV6dFCDr72_krpUlYaVKQSTRjw
GET http://localhost:3000/posts/1