POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoiZGVsZXRlQGdtYWlsLmNvbSIsImlhdCI6MTcyNzM0NjM2MiwiZXhwIjoxNzI3MzQ5OTYyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.S6n_ulKsZpzULzFkkHCMJMOrTN3vPBa6f0lsD12WXHA

{
  "userId": 6,
  "caption": "This is an amazing post...",
  "mediaUrl": "https://s3.aws.com/some-random-bucket/path-to-file/image.jpg",
  "location": "New York City, NYC"
}